apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-messaging-app-blue
  labels:
    app: django-messaging-app
    version: blue
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-messaging-app
      version: blue
  template:
    metadata:
      labels:
        app: django-messaging-app
        version: blue
        environment: production
    spec:
      containers:
      - name: django-messaging-app
        image: django-messaging-app:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: DEBUG
          value: "False"
        - name: ALLOWED_HOSTS
          value: "*"
        - name: DATABASE_URL
          value: "sqlite:///db.sqlite3"
        - name: VERSION_TAG
          value: "blue"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: secret-key
              optional: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: static-files
          mountPath: /app/staticfiles
        - name: media-files
          mountPath: /app/media
      volumes:
      - name: static-files
        persistentVolumeClaim:
          claimName: django-static-pvc
      - name: media-files
        persistentVolumeClaim:
          claimName: django-media-pvc
      restartPolicy: Always

---
apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
data:
  # Base64 encoded secret key - replace with your actual secret key
  # To generate: echo -n "your-secret-key-here" | base64
  secret-key: eW91ci1zZWNyZXQta2V5LWhlcmUtcmVwbGFjZS13aXRoLWFjdHVhbC1rZXk=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  DATABASE_URL: "sqlite:///db.sqlite3"
  # Add other configuration variables as needed
  DJANGO_SETTINGS_MODULE: "messaging_app.settings"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-media-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-static-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi